### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by 3t8** [dokc/rebuilding-explorers-world#12]
The [next.js](https://github.com/dokc/rebuilding-explorers-world/blob/main/nextjs.org) and [newsletter](https://docs.google.com/forms/d/e/1FAIpQLSeNTRsesRA7-1uMyFeHMMqfG9IgdVd7soY_L4wx5WqeDUcMjA/viewform) links in README.md are broken

**Comment by AbhijithGanesh** [comment]
@3t8 Thank you. We appreciate your efforts to the readme! I would like to know if you would like to add the patch

**Comment by 3t8** [comment]
Sure!
