### ISSUE TITLE
[ADD]: Add greeting messages

### ISSUE THREAD

**Issue by AbhijithGanesh** [dokc/rebuilding-explorers-world#8]
Currently the members aren't greeted by GitHub actions when they claim, to solve this issue one needs to implement a workflow to do so.

Tasks:
 - [ ] Implement a GitHub workflow to greet on comments
 - [ ] Add socials attached below

## Contact

Check out the [DoK Slack channel](https://dokcommunity.slack.com/archives/C029SP0H937) for updates and discussion. 
Checkout out the [Dok YouTube channel](https://www.youtube.com/channel/UCUnXJbHQ89R2uSfKsqQwGvQ) for more information, talks, discussions, and raps!!!
And sign up to the update

**Comment by 3t8** [comment]
I'd like to work on this. Is there any way you can check the newsletter link?

**Comment by AbhijithGanesh** [comment]
Can you add the link @3t8

**Comment by 3t8** [comment]
I'm not exactly sure what the right newsletter link would be

**Comment by AbhijithGanesh** [comment]
I am sorry , the news letter is deleted, you don't have to add it

**Comment by AbhijithGanesh** [comment]
I am sorry , the news letter is deleted, you don't have to add it

**Comment by 3t8** [comment]
I added an action to greet the users. Check https://github.com/3t8/rebuilding-explorers-world/issues/1
